- name: Relase Vagrant Box
  when: release
  block:
    - name: Check Vagrant Cloud login
      become: no
      command: "vagrant cloud auth login --check"
    
    - name: Set box version for rolling release
      set_fact:
        box_version: "{{ vyos_version.split('-')[2][0:8] }}.{{ vyos_version.split('-')[2][8:10] }}.{{ vyos_version.split('-')[2][10:12] }}"
      when:
        - box_version is undefined
        - vyos_version.split("-") | length == 3
    
    - name: Set box version for epa and rc
      set_fact:
        box_version: "{{ vyos_version.split('-')[0] }}"
      when:
        - box_version is undefined
        - vyos_version.split("-") | length == 2
    
    - name: Set box version for LTS release
      set_fact:
        box_version: "{{ vyos_version }}"
      when:
        - box_version is undefined
        - vyos_version.split("-") | length == 1
    
    - name: Create the Vagrant box provider
      become: no
      command: "vagrant cloud provider create {{ vyos_vagrant_box_name }} {{ vagrant_provider }} {{ box_version }} --no-tty"

    - name: Upload the Vagrant box
      become: no
      command: "vagrant cloud provider upload {{ vyos_vagrant_box_name }} {{ vagrant_provider }} {{ box_version }} {{ vyos_output_img }} --no-tty"
